name: deploy website
# on:
#   push:
#     branches:
#       - source
on: push

env:
  POETRY_HOME: /opt/poetry

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: "true"
      - uses: actions/setup-python@v3
        with:
          python-version: "3.7"

      - name: Install poetry
        run: |
          python3 -m venv $POETRY_HOME
          $POETRY_HOME/bin/pip install poetry==1.2.0

      - name: Install dependencies
        run: |
          poetry install --no-root

      - name: Install Task
        uses: arduino/setup-task@v1

      # - name: Build and publish
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      #     # PAT to enable the that happens in the task 'publish_https'
      #     GIT_PAT: ${{ secrets.MY_PAT }}
      #   run: |
      #     poetry run task publish_https
