name: deploy website
on:
  push:
    branches:
      - source

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: "true"
      - uses: actions/setup-python@v3
        with:
          python-version: "3.7"

      - name: Install pipenv
        uses: dschep/install-pipenv-action@v1

      - name: Install dependencies
        run: |
          pipenv install

      - name: Install Task
        uses: arduino/setup-task@v1

      - name: Build and publish
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GIT_PAT: ${{ secrets.MY_PAT }}
        run: |
          pipenv run task publish_https
